transformer:
  encoder_layer: 6 # changed from 7
  encoder_head: 2
  encoder_hidden: 256 # changed from 256 (32 for orig.) 16 for updated
  decoder_layer: 6 # changed from 6
  decoder_head: 2
  decoder_hidden: 256 # changed from 256 (32 for orig.) 16 for updated
  conv_filter_size: 1024 # changed from 1024 (1024 for orig.) 128 for updated
  conv_kernel_size: [9, 1]
  encoder_dropout: 0.2 # changed from 0.2 for updated
  decoder_dropout: 0.2 # cahnged from 0.2 for updated

variance_predictor:
  filter_size: 256 # changed from 256 (256 for orig.) 64 for updated
  kernel_size: 3
  dropout: 0.5 # changd from 0.5



variance_embedding:
  pitch_quantization: "linear" # support 'linear' or 'log', 'log' is allowed only if the pitch values are not normalized during preprocessing
  energy_quantization: "linear" # support 'linear' or 'log', 'log' is allowed only if the energy values are not normalized during preprocessing
  n_bins: 256

pause_embedding:
  n_bins: 128

# gst:
#   use_gst: False
#   conv_filters: [32, 32, 64, 64, 128, 128]
#   gru_hidden: 128
#   token_size: 128
#   n_style_token: 10
#   attn_head: 4

multi_speaker: False

max_seq_len: 1000

vocoder:
  model: "HiFi-GAN" # support 'HiFi-GAN', 'MelGAN'
  speaker: "LJSpeech" # support  'LJSpeech', 'universal'

# transformer:
#   encoder_layer: 2 # changed from 7
#   encoder_head: 2
#   encoder_hidden: 32 # changed from 256 (32 for orig.) 16 for updated
#   decoder_layer: 2 # changed from 6
#   decoder_head: 2
#   decoder_hidden: 32 # changed from 256 (32 for orig.) 16 for updated
#   conv_filter_size: 256 # changed from 1024 (1024 for orig.) 128 for updated
#   conv_kernel_size: [9, 1]
#   encoder_dropout: 0.2 # changed from 0.2 for updated
#   decoder_dropout: 0.2 # cahnged from 0.2 for updated

# variance_predictor:
#   filter_size: 128 # changed from 256 (256 for orig.) 64 for updated
#   kernel_size: 3
#   dropout: 0.5

# variance_embedding:
#   pitch_quantization: "linear" # support 'linear' or 'log', 'log' is allowed only if the pitch values are not normalized during preprocessing
#   energy_quantization: "linear" # support 'linear' or 'log', 'log' is allowed only if the energy values are not normalized during preprocessing
#   n_bins: 256

# multi_speaker: False

# max_seq_len: 1000

# vocoder:
#   model: "HiFi-GAN" # support 'HiFi-GAN', 'MelGAN'
#   speaker: "LJSpeech" # support  'LJSpeech', 'universal'
